### ISSUE TITLE
S3: metadatas and ACL correctly marshalled?

### ISSUE THREAD

**Issue by nremond** [sclasen/spray-aws#11]
Hi,

When uploading photos in JPEG using the following code, the ACL and the metadata are not correctly set when looking at the AWS S3 console.

Any help?

Thank you very much for open-sourcing this lib.
Cheers
Nicolas

``` scala
object S3Service {
  val endpoint = "https://s3-eu-west-1.amazonaws.com"
  val props = S3ClientProps(accessKeyId, secretKey, Timeout(30.seconds), system, system, endpoint)
  val client = new S3Client(props)

  val jpgMetadata = {
    val md = new ObjectMetadata
    md.setContentType("image/jpeg")
    md
  }

  def updateUserProfile(userId: Long, data: Array[Byte]): Future[Either[AmazonServiceException, ObjectMetadata]] = {
    val objectName = s"user-picture-profiles/$userId"
    client.putObject(new PutObjectRequest("my-bucket", objectName, new ByteArrayInputStream(data), jpgMetadata)
      .withCannedAcl(CannedAccessControlList.PublicRead))
  }
}
```

**Comment by sclasen** [comment]
@slomo any idea on this one?

**Comment by slomo** [comment]
@nremond That is correct I was a bit lazy implementing those since aws-sdk has very poor marshaller support for S3 and instead this must be dealt with in the client.

In order for the feature to work [this](https://github.com/aws/aws-sdk-java/blob/master/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L1345) must be included [here](https://github.com/sclasen/spray-aws/blob/master/spray-s3/src/main/scala/com/sclasen/spray/aws/s3/S3Client.scala#L65).

I could give it a try maybe next weekend, tough I can't promise anything (currently moving).

**Comment by nremond** [comment]
Yeah, I figured out something like that, I was looking at the REST doc:
http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html

I'll will provide a patch, I already mostly done.
